class Language
{
     static Map<String, String> get language => {
    'egovapp': 'EGOV APP',
    'egov-dashboard':'HỆ THỐNG QUẢN LÝ HÀNH CHÍNH ĐIỆN TỬ',
    'home': 'Trang chủ',
    'trinhbaocao': 'Trình (Báo cáo)',
    'totrinh': 'Tờ trình',
    'totrinhgui': 'Xử lý tờ trình gửi',
    'totrinhnhan': 'Xử lý tờ trình nhận',
    'totrinhdangsoan': 'Tờ trình đang soạn',
    'giaoviec': 'Giao việc (Yêu cầu)',
    'giaoviecgui': 'Xử lý giao việc gửi',
    'giaoviecnhan': 'Xử lý giao việc nhận',
    'giaoviecdangsoan':'Giao việc đang soạn',
    'homthunoibo': 'Hòm thư nội bộ',
    'thunhan': 'Thư nhận',
    'thudagui': 'Thư đã gửi',
    'thudangsoan':'Thư đang soạn',
    'thungrac': 'Thùng rác',
    'thamgiahop': 'Tham gia họp',
    'vanbanden': 'Văn bản đến',
    'vanbandenchogiaoxuly': 'Văn bản đến chờ giao xử lý',
    'vanbandendavaoso': 'Văn bản đến đã vào sổ',
    'vanbandenchuaxuly': 'Văn bản đến chưa xử lý',
    'vanbandendangxuly': 'Văn bản đến đang xử lý',
    'vanbandenhoanthanh': 'Văn bản đến đã hoàn thành',
    'tatcavanbanden':'Tất cả văn bản đến',
    'vanbandi': 'Văn bản đi',
    'vanbandichogiaoxuly': 'Văn bản đi chờ giao xử lý',
    'vanbandidavaoso': 'Văn bản đi đã vào sổ',
    'vanbandichuaxuly': 'Văn bản đi chưa xử lý',
    'vanbandidangxuly': 'Văn bản đi đang xử lý',
    'vanbandihoanthanh': 'Văn bản đi đã hoàn thành',
    'tatcavanbandi':'Tất cả văn bản đi',
    'xulyvanbandi': 'Xử lý văn bản đi',
    'docthongbao': 'Đọc thông báo',
    'quanlythongbao': 'Quản lý thông báo',
    'thongbao': 'Thông báo',
    'meeting': 'Cuộc họp',
    'email': 'Thư điện tử',
    'chuaxuly':'Chưa xử lý',
    'dangxuly': 'Đang xử lý',
    'hoanthanh': 'Hoàn thành',
    'soanthao': 'Soạn thảo',
    'lichcongtac': 'Lịch công tác',
    'lichcanhan': 'Lịch cá nhân',
    'lichdonvi': 'Lịch đơn vị',
    'chucnangchung': 'Chức năng chung',
    'kehoach': 'Kế hoạch',
    'hoptraodoithongtin': 'Họp trao đổi thông tin',
    'exit': 'Thoát khỏi ứng dụng',
    'nofounditems': 'Không tìm thấy thông tin nào',
    'error_access_api': 'Đã có lỗi truy cập dữ liệu',
    'error': 'Lỗi:',
    'thongtintotrinh': 'Thông tin tờ trình',
    'nguoichutri': 'Người chủ trì',
    'nguoitrinh': 'Người trình',
    'filedinhkem': 'File đính kèm',
    'thoigiangui': 'Thời gian gửi',
    'thoigianhoanthanh': 'Thời gian hoàn thành',
    'ykientonghop': 'Ý kiến tổng hợp',
    'ykienxuly':'Ý kiến xử lý',
    'add': 'Thêm mới',
    'delete': 'Xóa thông tin',
    'update': 'Sửa đổi',
     'assign': 'Giao xử lý',
     'updatedate': 'Thay đổi thời hạn',
     'hoanthanh': 'Hoàn thành',
     'thongtinxuly': 'Thông tin xử lý',
     'solandoc': 'Số lần đọc',
     'name_empty': 'Không tên',
     'select_donvi': 'Chọn đơn vị',
     'select_user': 'Chọn user',
     'select_hint_donvi': 'Vui lòng chọn đơn vị cần tìm',
     'chude': 'Chủ đề',
     'nguoinhan': 'Người nhận',
     'thoihan': 'Thời hạn',
     'required_empty': ' không được trống!',
     'save': 'Lưu dữ liệu',
     'capnhattotrinh': 'Cập nhật tờ trình',
     'select_nguoinhan': 'Chọn người nhận',
     'refresh': 'Làm mới',
     'processing_data': 'Hệ thống đang xử lý dữ liệu!',
     'download_acttach': 'Tải file đính kèm',
     'permission_storage': 'Vui lòng bật quyền truy cập',
     'error_open_file': 'Không thể mở file. Vui lòng kiểm tra lại!',
     'list_attch': 'Danh sách file đính kèm',
     'progress_action': 'Hệ thống đang xử lý dữ liệu...',
     'progress_login': 'Hệ thống đang xác thực thông tin...',
     'progress_load': 'Hệ thống đang tải dữ liệu...',
      'input_content': 'Nhập nội dung',
      'message_insert_success': 'Đã thêm mới dữ liệu thành công!',
       'message_send_success': 'Đã gửi thông tin thành công!',
      'message_update_success': 'Đã cập nhật dữ liệu thành công!',
      'message_delete_success': 'Đã xóa dữ liệu thành công',
      'message_error': 'Đã có lỗi xảy ra. Vui lòng kiểm tra lại!',
      'create_totrinh': 'Soạn tờ trình',
      'draft': 'Lưu nháp' ,
      'send': 'Gửi',
      'yes': 'Đồng ý',
      'no': 'Hủy',
      'alert': 'Thông báo',
      'message_delete_question': 'Bạn muốn xóa thông tin này?',
      'totrinh_add': 'Soạn tờ trình',
      'sendtotrinh': 'Gửi tờ trình',
      'message_save_question': 'Bạn muốn lưu thông tin này?',
       'message_send_question': 'Bạn muốn gửi thông tin này?',
       'message_success_ykien_status': 'Đã ý kiến xử lý và chuyển trạng thái hoàn thành thành công!',
       'message_success_ykien': 'Đã lưu thông tin ý kiến xử lý thành công!',
       'question_ykien_status': 'Bạn muốn lưu ý kiến xử lý và chuyển trạng thái hoàn thành?',
       'question_ykien': 'Bạn muốn lưu ý kiến xử lý?',
       'save_ykien': 'Lưu ý kiến', 
       'save_hoanthanh': 'Hoàn thành',
       'question_delete_file': 'Bạn muốn xóa file này?',
       'change':'Thay đổi',
       'message_change_date_success':'Đã thay đổi thời hạn thành công!',
       'question_delete_user': 'Bạn muốn xóa thống tin user này',
       'danhsachnhansu': 'Danh sách nhân sự',
       'select_workgroup': 'Chọn nhóm gửi',
       'workgroup': 'Nhóm gửi',
       'danhsachnhomgui': 'Danh sách nhóm gửi',
       'create_yeucau':'Soạn giao việc',
       'yeucau_add': 'Thêm mới giao việc',
       'capnhatyeucau': 'Cập nhật yêu cầu',
       'chophepthamkhao': 'Cho phép tham khảo ý kiến',
       'message_hoanthanh_question':'Bạn phải chắc chắn mình đã xử lý xong công việc này. Nhấn Đồng ý để xác nhận hoàn thành, Hủy để xem lại.',
       'change_hoanthanh_success': 'Đã chuyển trạng thái hoàn thành thành công!',
       'assign_staff_xuly':'Giao xử lý',
       'assign_staff_xuly_question': 'Bạn muốn giao xử lý?',
       'message_add_nguoinhan_success': 'Đã thêm thông tin người nhận thành công!',
       'khongchophepthamkhao': 'Không cho phép tham khảo ý kiến',
       'xulyyeucau':'Xử lý yêu cầu',
       'xulylai': 'Xử lý lại',
       'message_xulylai_question': 'Nếu bạn bấm OK, Văn bản sẽ đặt trạng thái cho người nhận là chưa xem, chưa xử lý để xem yêu cầu xử lý lại của bạn. Bấm Cancel để hủy lệnh',
       'message_xulylai_success': 'Đã thiết lập xử lý lại văn bản thành công!',
       'alert_yeucau_success': 'Yêu cầu đã được hoàn thành bạn không thể thêm ý kiến!',
       'alert_totrinh_success': 'Tờ trình đã được hoàn thành bạn không thể thêm ý kiến!',
       'chuyentrinh': 'Chuyển trình',
       'chenhoso':'Chèn hồ sơ',
       'chuyengiaoviec':'Chuyển giao việc',
       'xulytotrinh':'Xử lý tờ trình',
       'sovaoso':'Số vào sổ',
       'sohieugoc': 'Số hiệu gốc',
       'loaivanban':'Loại văn bản',
       'trichyeu':'Trích yếu',
       'ghichu':'Ghi chú',
       'linhvucvanban':'Lĩnh vực văn bản',
       'domat':'Độ mật',
       'dokhan':'Độ khẩn',
       'ngayky':'Ngày ký',
       'nguoiky':'Người ký',
       'ngaynhan':'Ngày nhận',
       'ngayvaoso':'Ngày vào sổ',
       'select_noigui':'Chọn nơi gửi',
       'select_loaivanban':'Chọn loại văn bản',
       'select_linhvucvanban':'Chọn lĩnh vực văn bản',
       'select_domat':'Chọn độ mật',
       'select_dokhan':'Chọn độ khẩn',
       'noigui':'Nơi gửi',
       'create_vanbanden':'Vào sổ văn bản đến',
       'select_empty':'Vui lòng chọn ',
       'phocapkhonggiao': 'Phổ cập, không giao, lưu hệ thống',
       'khongxuly': 'Không xử lý',
       'guidichdanh':'Gửi đích danh',
       'tralaivanthu':'Trả lại văn thư',
       'chogiaoxuly':'Chờ giao xử lý',
       'nguoigiaohoanthanh':'Người giao hoàn thành luôn',
       'theodoixulycaptiep': 'Theo dõi xử lý đến cấp nhận giao tiếp',
       'butphe':'Bút phê',
       'message_giaoxuly_vanban_success': 'Đã giao xử lý văn bản thành công!',
       'assign_vanban_question':'Bạn muốn giao xử lý văn bản này?',
       'select_empty_required':'Vui lòng chọn người xử lý!',
       'giaoxulyvanbanden':'Giao xử lý văn bản đến',
       'xulyvanbanden':'Xử lý văn bản đến',
       'capnhatvanbanden':'Cập nhật văn bản đến',
       'note_required':'Trường màu đỏ là trường bắt buộc nhập!',
       'butphelanhdao':'Bút phê của lãnh đạo',
       'ketquaxulynguoichutri': 'Kết quả xử lý của người chủ trì',
       'xemvanban':'Xem văn bản',
       'xemtotrinh':'Xem tờ trình',
       'create_vanbandi':'Vào sổ văn bản đi',
       'nhomvanban': 'Nhóm văn bản',
       'select_nhomvanban': 'Chọn nhóm văn bản',
       'message_error_assiger':"Vui lòng chọn người ký!",
       'giaoxulyvanbandi':'Giao xử lý văn bản đi',
       'xulyvanbandi':'Xử lý văn bản đi',
       'capnhatvanbandi':'Cập nhật văn bản đi',
       'select_nguoiky':'Chọn người ký',
       'donvinhan':'Đơn vị nhận',
       'select_donvinhan':'Chọn đơn vị nhận',
       'message_error_donvinhan':'Vui lòng chọn đơn vị nhận!',
       'danhsach_meeting':'Danh sách cuộc họp',
       'create_meeting':'Tạo cuộc họp',
       'select_nguoihop':'Chọn người họp',
       'chophepthamkhaohop':'Chép các thành viên tham khảo ý kiến',
       'message_add_nguoihop_success': 'Đã thêm thông tin người họp thành công!',
       'assign_staff_hop_question': 'Bạn muốn thêm người họp?',
       'assign_staff_hop':'Thêm người họp',
       'message_add_nguoihop_success': 'Đã thêm thông tin người họp thành công!',
       'ketthuc':'Kết thúc',
       'assignhop':'Thêm người họp',
       'change_ketthuc_success': 'Đã chuyển trạng thái kết thúc cuộc họp thành công!',
       'capnhatmeeting':'Cập nhật cuộc họp',
       'thongtincuochop':'Thông tin cuộc họp',
       'hoptraodoithongtin':'Họp trao đổi thông tin',
       'thamgiahop':'Tham gia họp',
       'docthongbao':'Đọc thông báo',
       'qlthongbao':'Quản lý thông báo',
       'danhsach_thongbao':'Danh sách thông báo',
       'create_thongbao':'Tạo thông báo',
       'select_nguoidoc':'Chọn người đọc',
       'ngayhieuluc':'Ngày hiệu lực',
       'ngayhiethieuluc':'Ngày hết hiệu lục',
       'assign_staff_thongbao_question': 'Bạn muốn thêm người nhận thông báo?',
       'assign_staff_thongbao':'Thêm người nhận thông báo',
       'capnhatthongbao':'Cập nhật thông báo',
       'alert_thongbao_success': 'Thông báo đã hết hạn bạn không thể thêm ý kiến!',
       'noidung':'Nội dung',
       'thongtinthongbao':'Thông tin thông báo',
       'danhsach_kehoach':'Danh sách kế hoạch',
       'create_kehoach':'Tạo kế hoạch',
       'tenkehoach':'Tên kế hoạch',
       'loaikehoach':'Loại kế hoạch',
       'select_loaikehoach':'Chọn loại kế hoạch',
       'message_save_vanbanphapquy_question': 'Bạn muốn lưu thông tin văn bản pháp quy này?',
      'message_save_kehoach_question': 'Bạn muốn lưu thông tin kế hoạch này?',
      'message_save_mauvanban_question': 'Bạn muốn lưu thông tin mẫu văn bản này?',
       'message_save_thongbao_question': 'Bạn muốn lưu thông tin thông báo này?',
       'message_save_meeting_question': 'Bạn muốn lưu thông tin cuộc họp này?',
       'thongtinkehoach':'Thông tin kế hoạch',
       'capnhatkehoach':'Cập nhật kế hoạch',
       'xemfiledinhkem':'Xem file đính kèm',
       'luotnguoidoc':'Lượt người đọc',
       'danhsach_vanbanphapquy':'Danh sách văn bản pháp quy',
       'create_vanbanphapquy':'Thêm mới văn bản pháp quy',
       'noiguiphathanh':'Nơi gửi phát hành',
       'capnhatvanbanphapquy':'Cập nhật văn bản pháp quy',
       'create_email':'Soạn thư',
       'save_draft':'Lưu nháp',
       'message_save_email_question':'Bạn muốn lưu thư này?',
       'message_send_email_question':'Bạn muốn gửi thư này?',
       'guirangoai':'Gửi ra ngoài',
       'capnhatemail':'Cập nhật thư',
       'thongtinthu':'Thông tin thư',
       'nguoigui':'Người gửi',
       'phanhoi':'Phản hồi',
       'message_send_mail_success':'Thư đã được gửi thành công!',
       'guitiep':'Gửi tiếp',
       'traloi':'Trả lời',
       'traloitatca':'Trả lời tất cả',
       'ghimthu':'Ghim thư',
       'huyghimthu':'Hủy ghim thư',
       'message_ghimthu_question':'Bạn muốn ghim thư này?',
       'message_ghimthu_success':'Đã ghim thư thành công',
       'message_unghimthu_question':'Bạn muốn hủy ghim thư này?',
        'message_unghimthu_success':'Đã hủy ghim thư thành công',
       'thongtinthugui':'Thông tin thư gửi',
       'message_restore_question':'Bạn muốn phục hồi thư đã xóa này?',
       'message_restore_tatca_question':'Bạn muốn phục hồi tất cả thư đã xóa?',
       'message_delete_vinhvien_question':'Bạn muốn xóa vinh viễn thư này ?',
       'message_delete_tatca_vinhvien_question':'Bạn muốn xóa tất cả thư đã xóa vinh viễn?',
       'message_delete_vinhvien_success':'Đã xóa vĩnh viễn thư này thành công!',
       'message_restore_success':'Đã phục hồi thư đã xóa thành công',
       'message_delete_thu_success':'Đã xóa thư trong thùng rác thành công!',
       'phuchoi':'Phục hồi',
       'phuchoitatca':'Phục hồi tất cả',
       'deleteselect':'Xóa mục chọn',
       'deleteall':'Xóa tất cả',
       'thungracthudagui':'Thùng rác thư gửi',
       'thungracthudanhan':'Thùng rác thư nhận',
       'year':'Năm',
       'week':'Tuần',
       'select_week':'Chọn tuần xem lịch',
       'select_year':'Chọn năm',
       'monday':"Thứ hai",
       'tuesday':"Thứ ba",
       'wednesday':"Thứ tư",
       'thursday':"Thứ năm",
       'friday':"Thứ sáu",
       'saturday':"Thứ bảy",
       'sunday':"Chủ nhật",
       'thoigian':'Thời gian',
       'diadiem':'Địa điểm',
       'create_calendar':'Tạo lịch',
       'select_color':'Chọn màu',
       'thongtinlichcongtac':'Thông tin lịch công tác',
       'thoigiantu':'Thời gian từ',
       'thoigianden':'Thời gian đến',
       'message_save_lichcongtac_question':'Bạn muốn lưu thông tin lịch công tác này?',
       'message_save_lichcongtac_success':'Đã lưu thông tin lịch công tác thành công!',
       'message_save_lichdonvi_question':'Bạn muốn lưu thông tin lịch đơn vị này?',
       'message_save_lichdonvi_success':'Đã lưu thông tin lịch đơn vị thành công!',
       'message_save_canhan_question':'Bạn muốn lưu thông tin lịch cá nhân này?',
       'message_save_canhan_success':'Đã lưu thông tin lịch cá nhân thành công!',
       'tungay':'Từ ngày',
       'tugio':'Từ giờ',
       'denngay':'Đến ngày',
       'dengio':'Đến giờ',
       'capnhatlichcongtac':'Cập nhật lịch công tác',
       'thongtinlichdonvi':'Thông tin lịch đơn vị',
       'capnhatlichdonvi':'Cập nhật lịch đơn vị',
       'thongtinlichcanhan':'Thông tin lịch cá nhân',
       'capnhatlichcanhan':'Thông tin lịch cá nhân',
       'username':'Tên đăng nhập',
       'password':'Mật khẩu',
       'login':'Đăng nhập hệ thống',
       'close':'Đóng',
       'error_login':'Tên đăng nhập hoặc mật khẩu không đúng vui lòng kiểm tra lại!',
       'vbdenchuaxuly':'VB đến chưa xử lý',
       'vbdendangxuly':'VB đến đang xử lý',
       'vbdenhoanthanh':'VB đến hoàn thành',
       'vbdentatca':'Tất cả văn bản đến',
       'vbdichuaxuly':'VB đi chưa xử lý',
       'vbdidangxuly':'VB đi đang xử lý',
       'vbdihoanthanh':'VB đi hoàn thành',
       'vbditatca':'Tất cả văn bản đi',
       'tainguyen':'Tài nguyên',
       'vanbanphapquy':'Văn bản pháp quy',
       'vanbanphocap':'Văn bản phổ cập',
       'mauvanban':'Mẫu văn bản',
       'hosocongviec':'Hồ sơ công việc',
       'hosocanhan':'Hồ sơ cá nhân',
       'hosodonvi':'Hồ sơ đơn vị',
       'hosoluutru':'Hồ sơ lưu trữ',
       'datxe':'Đặt xe',
       'xemketquaduyet':'Xem kết quả duyệt',
       'duyetyeucau':'Duyệt yêu cầu',
       'theodoiyeucau':'Theo dõi yêu cầu',
       'dangkylich':'Đăng ký lịch',
       'ketquaxeplichphong':'Kết quả xếp lịch phòng',
       'sapxeplich':'Sắp xếp lịch',
       'theodoidatlich':'Theo dõi đặt lịch',
       'totrinhdangxuly':'Tờ trình đang xử lý',
       'totrinhchuaxuly':'Tờ trình chưa xử lý',
       'totrinhhoanthanh':'Tờ trình hoàn thành',
       'giaoviecdangxuly':'Yêu cầu đang xử lý',
       'giaoviecchuaxuly':'Yêu cầu chưa xử lý',
       'giaoviechoanthanh':'Yêu cầu đã hoàn thành',
       'thongbaomoi':'Thông báo mới',
       'cuochopmoi':'Cuộc họp mới',
       'lichcongtacmoi':'Lịch công tác mới',
       'lichdonvimoi':'Lịch đơn vị mới',
       'thumoinhan':'Thư mới nhận',
       'tatcathongbao':'Tất cả thông báo',
       'share':'Chia sẽ',
       'danhsach-mauvanban':'Danh sách mẫu văn bản',
       'create_mauvanban':'Tạo mẫu văn bản',
       'nhommauvanban':'Nhóm mẫu văn bản',
       'tenmauvanban':'Tên mẫu văn bản',
       'capnhatmauvanban':'Cập nhật mẫu văn bản',
       'thongtinvanbanphapquy':'Thông tin văn bản pháp quy',
      'thongtinmauvanban':'Thông tin mẫu văn bản',
      'dangkythietbi':'Đăng ký thiết bị',
      'ngay':'Ngày',
      'select_nhommauvanban':'Chọn nhóm mẫu văn bản',
      'select_nguoiduyet':'Chọn người duyệt',
      'yeucautraloi':'Yêu cầu trả lời',
      'noidungpheduyet':'Nội dung phê duyệt',
      'capnhatdangkythietbi':'Cập nhật đăng ký thiết bị',
      'message_success_approve_status':'Thông tin đã được phê duyệt thành công!',
      'message_success_reject_status':'Thông tin đã từ chối thành công!',
      'question_approved_status':'Bạn muốn phê duyệt thông tin này?',
      'question_reject_status':'Bạn muốn từ chối thông tin này?',
      'save_approved':'Phê duyệt',
      'save_reject':'Từ chối',
      'thongtindangky':'Thông tin đăng ký',
      'thongtinpheduyet':'Thông tin phê duyệt',
      'ykienpheduyettuchoi':'Ý kiến phê duyệt hoặc từ chối',
      'dangkyphonghop':'Đăng ký phòng họp',
      'select_phong':'Chọn phòng họp',
      'phong':'Phòng họp',
      'message_save_phonghop_question':'Bạn muốn lưu thông tin đăng ký phòng họp này?',
      'message_save_thietbi_question':'Bạn muốn lưu thông tin đăng ký thiết bị này?',
      'capnhatdangkyphonghop':'Cập nhật đăng ký phòng họp',
      'tuchoi':'Bị từ chối',
      'dapheduyet':'Đã phê duyệt',
      'chopheduyet':'Chờ phê duyệt',
      'danhsach_hosodonvi':'Danh sách hồ sơ đơn vị',
      'danhsach_hosocanhan':'Danh sách hồ sơ cá nhân',
      'danhsach_hosoluutru':'Danh sách hồ sơ lưu trữ',
      'create_hoso':'Tạo hồ sơ',
      'message_hoso_success': 'Đã tạo thông tin hồ sơ thành công!',
      'tenhoso':'Tên hồ sơ',
      'message_save_hoso_question':'Bạn muốn lưu thông tin hồ sơ này?',
      'nguoitao':'Người tạo',
      'thongtinhoso':'Thông tin hồ sơ',
      'capnhathosodonvi':'Cập nhật hồ sơ đơn vị',
      'foldersave':'Thư mục lưu trữ',
      'capnhathosocanhan':'Cập nhật hồ sơ cá nhân',
      'message_share_hoso_success':'Đã chia sẽ hồ sơ thành công!',
      'share_staff_hoso_question':'Bạn muốn chia sẽ thông tin hồ sơ này?',
      'noidungtrinh':'Nội dung trình',
      'noidunggiaoviec':'Nội dung giao việc',
      'message_chenhoso_success':'Đã chèn thông tin vào hồ sơ thành công!',
      'message_chenhoso_question':'Bạn muốn chèn thông tin vào hồ sơ?',
      'danhsachhoso':'Danh sách hồ sơ',
      'message_update_staff_success':'Đã thay đổi thông tin tài khoản thành công!',
      'hodem':'Họ đệm',
      'ten':'Tên',
      'bidanh':'Bí danh',
      'ngaysinh':'Ngày sinh',
      'mobile':'Di động',
      'gioitinh':'Giới tính',
      'teloffice':'Điện thoại văn phòng',
      'telhome':'Điện thoại nhà riêng',
      'address':'Địa chỉ nhà riêng',
      'male':'Nam',
      'female':'Nữ',
      'message_save_profile_question':'Bạn muốn thay đổi thông tin tài khoản?',
      'info_account':'Thông tin tài khoản',
      'change_avatar':'Đổi ảnh đại diện',
      'change_password':'Đổi mật khẩu',
      'passwordnew':'Mật khẩu mới',
      'passwordconfirm':'Nhập lại mật khẩu',
      'thaydoithongtinmatkhau':'Thay đổi thông tin mật khẩu',
      'message_save_change_password_question':'Bạn muốn thay đổi thông tin mật khẩu?',
      'message_change_password_success':'Đã thay đổi thông tin mật khẩu thành công!',
      'save_info':'Lưu thông tin',
      'caidat':'Cài đặt',
      'capnhatanhdaidien':'Cập nhật ảnh đại điện',
      'message_change_avatar_success':'Đã cập nhật ảnh đại diện thành công!',
      'danhsach-vanbanphapquy':'Danh sách văn bản pháp quy',
      'vohan':'Vô hạn'











  };
  static String getText(String key)
  {
    return language[key].toString();
  }
}
